//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionAbscences.Langagues {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GestionAbscences.Langagues.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1/2 day.
        /// </summary>
        public static string _1_2journée {
            get {
                return ResourceManager.GetString("1/2journée", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1.5 days.
        /// </summary>
        public static string _1_5journée {
            get {
                return ResourceManager.GetString("1.5journée", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1st tranche.
        /// </summary>
        public static string _1eretranche {
            get {
                return ResourceManager.GetString("1eretranche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1 day.
        /// </summary>
        public static string _1journée {
            get {
                return ResourceManager.GetString("1journée", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2 days.
        /// </summary>
        public static string _2_journée {
            get {
                return ResourceManager.GetString("2 journée", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2nd tranche.
        /// </summary>
        public static string _2èmetranche {
            get {
                return ResourceManager.GetString("2èmetranche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Accept.
        /// </summary>
        public static string Accepter {
            get {
                return ResourceManager.GetString("Accepter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Addons.
        /// </summary>
        public static string Addons {
            get {
                return ResourceManager.GetString("Addons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Assignment.
        /// </summary>
        public static string Affectation {
            get {
                return ResourceManager.GetString("Affectation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à cancel.
        /// </summary>
        public static string Annuler {
            get {
                return ResourceManager.GetString("Annuler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Arabic.
        /// </summary>
        public static string Arabic {
            get {
                return ResourceManager.GetString("Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à TO.
        /// </summary>
        public static string AU {
            get {
                return ResourceManager.GetString("AU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Authentication.
        /// </summary>
        public static string Authentification {
            get {
                return ResourceManager.GetString("Authentification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à change password.
        /// </summary>
        public static string changerlemotdepasse {
            get {
                return ResourceManager.GetString("changerlemotdepasse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CHOICE OF LEAVE.
        /// </summary>
        public static string CHOIXDECONGÉ {
            get {
                return ResourceManager.GetString("CHOIXDECONGÉ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Class.
        /// </summary>
        public static string Classe {
            get {
                return ResourceManager.GetString("Classe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à client dashboard.
        /// </summary>
        public static string clientdashboard {
            get {
                return ResourceManager.GetString("clientdashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Core.
        /// </summary>
        public static string Core {
            get {
                return ResourceManager.GetString("Core", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create New.
        /// </summary>
        public static string Create_New {
            get {
                return ResourceManager.GetString("Create New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date of creation DC.
        /// </summary>
        public static string DatecreationDC {
            get {
                return ResourceManager.GetString("DatecreationDC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start.
        /// </summary>
        public static string Debut {
            get {
                return ResourceManager.GetString("Debut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Deaths.
        /// </summary>
        public static string Décès {
            get {
                return ResourceManager.GetString("Décès", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Leave Request.
        /// </summary>
        public static string DemandeDeCongé {
            get {
                return ResourceManager.GetString("DemandeDeCongé", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Designation.
        /// </summary>
        public static string Designation {
            get {
                return ResourceManager.GetString("Designation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ltr.
        /// </summary>
        public static string dir {
            get {
                return ResourceManager.GetString("dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à FROM.
        /// </summary>
        public static string DU {
            get {
                return ResourceManager.GetString("DU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Length of Leave.
        /// </summary>
        public static string DuréedeCongé {
            get {
                return ResourceManager.GetString("DuréedeCongé", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Employee.
        /// </summary>
        public static string Employé {
            get {
                return ResourceManager.GetString("Employé", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Employe DataTable.
        /// </summary>
        public static string Employe_DataTable {
            get {
                return ResourceManager.GetString("Employe DataTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à EXCEPTIONAL/CR.
        /// </summary>
        public static string EXCEPTIONNEL_CR {
            get {
                return ResourceManager.GetString("EXCEPTIONNEL/CR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à EXCEPTIONAL A.BALANCE.
        /// </summary>
        public static string EXCEPTIONNELA_SOLDE {
            get {
                return ResourceManager.GetString("EXCEPTIONNELA.SOLDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à End.
        /// </summary>
        public static string Fin {
            get {
                return ResourceManager.GetString("Fin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Frensh.
        /// </summary>
        public static string Frensh {
            get {
                return ResourceManager.GetString("Frensh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à H.S.
        /// </summary>
        public static string H_S {
            get {
                return ResourceManager.GetString("H.S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hours.
        /// </summary>
        public static string Heures {
            get {
                return ResourceManager.GetString("Heures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à History.
        /// </summary>
        public static string Historique {
            get {
                return ResourceManager.GetString("Historique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Leave Request History.
        /// </summary>
        public static string HistoriquedesDemandedeConge {
            get {
                return ResourceManager.GetString("HistoriquedesDemandedeConge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à History of leave requests from.
        /// </summary>
        public static string Historiquedesdemandesdecongesde {
            get {
                return ResourceManager.GetString("Historiquedesdemandesdecongesde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Identifier.
        /// </summary>
        public static string Identifiant {
            get {
                return ResourceManager.GetString("Identifiant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Print title.
        /// </summary>
        public static string Imprimertitre {
            get {
                return ResourceManager.GetString("Imprimertitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Interface.
        /// </summary>
        public static string Interface {
            get {
                return ResourceManager.GetString("Interface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à J.F.
        /// </summary>
        public static string J_F {
            get {
                return ResourceManager.GetString("J.F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à J.R.
        /// </summary>
        public static string J_R {
            get {
                return ResourceManager.GetString("J.R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à days.
        /// </summary>
        public static string Jours {
            get {
                return ResourceManager.GetString("Jours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Layouts.
        /// </summary>
        public static string Layouts {
            get {
                return ResourceManager.GetString("Layouts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Light Sidenav.
        /// </summary>
        public static string LightSidenav {
            get {
                return ResourceManager.GetString("LightSidenav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à List of Employees.
        /// </summary>
        public static string Liste_des_Employés {
            get {
                return ResourceManager.GetString("Liste des Employés", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Wedding.
        /// </summary>
        public static string Mariage {
            get {
                return ResourceManager.GetString("Mariage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Personnel number.
        /// </summary>
        public static string Matricule {
            get {
                return ResourceManager.GetString("Matricule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mle.
        /// </summary>
        public static string Mle {
            get {
                return ResourceManager.GetString("Mle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit.
        /// </summary>
        public static string Modifier {
            get {
                return ResourceManager.GetString("Modifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Birth.
        /// </summary>
        public static string Naissance {
            get {
                return ResourceManager.GetString("Naissance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name &amp; Surname.
        /// </summary>
        public static string Nom_Prenom {
            get {
                return ResourceManager.GetString("Nom&Prenom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Number of days of leave of.
        /// </summary>
        public static string Nombredejourdecongesde {
            get {
                return ResourceManager.GetString("Nombredejourdecongesde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Number of days remaining.
        /// </summary>
        public static string NombredejourRestants {
            get {
                return ResourceManager.GetString("NombredejourRestants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Number of days remaining.
        /// </summary>
        public static string Nombredejoursquireste {
            get {
                return ResourceManager.GetString("Nombredejoursquireste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Total number of days.
        /// </summary>
        public static string Nombredejourtotal {
            get {
                return ResourceManager.GetString("Nombredejourtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Full name.
        /// </summary>
        public static string Nomcomplet {
            get {
                return ResourceManager.GetString("Nomcomplet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Observation.
        /// </summary>
        public static string Observation {
            get {
                return ResourceManager.GetString("Observation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pages.
        /// </summary>
        public static string Pages {
            get {
                return ResourceManager.GetString("Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Profil.
        /// </summary>
        public static string Profil {
            get {
                return ResourceManager.GetString("Profil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à RECOVERY.
        /// </summary>
        public static string RECUPERATION {
            get {
                return ResourceManager.GetString("RECUPERATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Refuse.
        /// </summary>
        public static string Refuser {
            get {
                return ResourceManager.GetString("Refuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à REGULAR.
        /// </summary>
        public static string REGULIER {
            get {
                return ResourceManager.GetString("REGULIER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Residual.
        /// </summary>
        public static string Reliquat {
            get {
                return ResourceManager.GetString("Reliquat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à WITHOUT BALANCE.
        /// </summary>
        public static string SANSSOLDE {
            get {
                return ResourceManager.GetString("SANSSOLDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Login.
        /// </summary>
        public static string SeConnecté {
            get {
                return ResourceManager.GetString("SeConnecté", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Logout.
        /// </summary>
        public static string SeDeconnecté {
            get {
                return ResourceManager.GetString("SeDeconnecté", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Static Navigation.
        /// </summary>
        public static string StaticNavigation {
            get {
                return ResourceManager.GetString("StaticNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type of leave.
        /// </summary>
        public static string Type_de_congé {
            get {
                return ResourceManager.GetString("Type de congé", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Validation N+1.
        /// </summary>
        public static string ValidationN_1 {
            get {
                return ResourceManager.GetString("ValidationN+1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Validation N+2.
        /// </summary>
        public static string ValidationN_2 {
            get {
                return ResourceManager.GetString("ValidationN+2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Validation RH.
        /// </summary>
        public static string ValidationRH {
            get {
                return ResourceManager.GetString("ValidationRH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Validate.
        /// </summary>
        public static string Valider {
            get {
                return ResourceManager.GetString("Valider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à your decision.
        /// </summary>
        public static string votre_décision {
            get {
                return ResourceManager.GetString("votre décision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your request is being processed..
        /// </summary>
        public static string Votredemandeestencoursdetraitement {
            get {
                return ResourceManager.GetString("Votredemandeestencoursdetraitement", resourceCulture);
            }
        }
    }
}
