//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionAbscences.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CumulRecup
    {
        public int IDCumulRecup { get; set; }
        public byte[] CumulHr { get; set; }
        public Nullable<float> CumulJF { get; set; }
        public Nullable<float> CumulR { get; set; }
        public Nullable<int> Mois { get; set; }
        public Nullable<int> Annee { get; set; }
        public Nullable<int> IDEmploye { get; set; }
    }
}
