//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionAbscences.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class demandeconge
    {
        public int idDemandeConge { get; set; }
        public Nullable<System.DateTime> DateDebut { get; set; }
        public Nullable<System.DateTime> DateFin { get; set; }
        public Nullable<System.DateTime> DateDC { get; set; }
        public string ValidationN1 { get; set; }
        public string ValidationN2 { get; set; }
        public int IdEmploye { get; set; }
        public int IdtypeConge { get; set; }
        public string justification { get; set; }
        public string ValdationRH { get; set; }
        public string annulation { get; set; }
        public Nullable<System.DateTime> DateValidationN1 { get; set; }
        public Nullable<System.DateTime> DateValidationN2 { get; set; }
        public Nullable<System.DateTime> DateValidationRH { get; set; }
        public string soldeConge { get; set; }
    
        public virtual employe employe { get; set; }
        public virtual typeconge typeconge { get; set; }
    }
}
